export const wrapPaginate = 'flex justify-center'
export const stylePaginate = 'relative flex rounded-md text-gray py-4'
export const pageLinkClassName = 'border-gray-300 relative inline-flex items-center h-[38px] px-4 py-2 border text-base font-medium hover:bg-gray-100 focus:bg-gray-100'
export const activeLinkClassName = 'bg-secondary-100 border-secondary-400 text-secondary border-secondary'
export const breakClassName = 'border-gray-300 relative inline-flex items-center px-4 border text-base font-medium'
export const styleIcon = 'relative inline-flex items-center px-2 py-2 border border-gray-300 bg-white text-base font-medium hover:bg-gray-100'
export const styleChevronIcon = 'h-5 w-5'