export const styleTitle = 'flex justify-center mb-3 text-2xl text-white'
export const styleWrap = 'flex justify-center'
export const styleContent = 'flex rounded-lg bg-gray-400 bg-opacity-50 items-center justify-between w-2/3 h-14 mx-6 px-8 mt-2 text-white'
export const styleEyeIcon = 'ml-3 h-6 w-6 text-gray-700 hover:text-gray-900'
export const styleText = 'flex justify-center mb-3 text-xl text-white'